import { Badge, type BadgeProps } from "@/components/ui/badge";

const labels: Record<string, string> = {
  active: "активный",
  new: "новый",
  loyal: "постоянный",
  inactive: "давно не возвращался",
  dayOff: "выходной",
  vacation: "отпуск",
  dismissed: "уволен",
  attention: "требует внимания",
  planned: "запланирована",
  confirmed: "подтверждена",
  inProgress: "в работе",
  completed: "завершена",
  cancelled: "отменена",
  refunded: "возврат",
  partiallyRefunded: "частичный возврат",
  noShow: "неявка",
  ok: "достаточно",
  low: "заканчивается",
  critical: "критический остаток",
  out: "нет в наличии",
  free: "свободен",
  busy: "занят",
  maintenance: "обслуживание",
  unavailable: "недоступен",
  draft: "черновик",
  scheduled: "запланирована",
  ending: "скоро завершится",
  finished: "завершена",
  paused: "остановлена",
  waiting: "ожидает",
  done: "выполнена",
  overdue: "просрочена",
  "priority-low": "низкий",
  "priority-medium": "средний",
  "priority-high": "высокий",
  enabled: "включён",
  hidden: "скрыт из меню",
  disabled: "отключён",
  owner: "владелец",
  admin: "администратор",
  employee: "сотрудник",
  connected: "подключено",
  disconnected: "не подключено",
  soon: "скоро",
  setup: "требует настройки",
  pending: "ожидает",
  accepted: "принято",
  expired: "истекло"
};

const variants: Record<string, BadgeProps["variant"]> = {
  active: "success",
  loyal: "success",
  completed: "success",
  done: "success",
  ok: "success",
  free: "success",
  connected: "success",
  new: "default",
  planned: "default",
  confirmed: "default",
  scheduled: "default",
  enabled: "success",
  inProgress: "warning",
  low: "warning",
  ending: "warning",
  waiting: "warning",
  "priority-low": "secondary",
  "priority-medium": "warning",
  setup: "warning",
  pending: "warning",
  accepted: "success",
  expired: "danger",
  attention: "danger",
  "priority-high": "danger",
  inactive: "warning",
  dayOff: "warning",
  vacation: "secondary",
  dismissed: "secondary",
  critical: "danger",
  out: "danger",
  unavailable: "danger",
  disabled: "danger",
  overdue: "danger",
  cancelled: "secondary",
  refunded: "warning",
  partiallyRefunded: "warning",
  noShow: "danger",
  hidden: "secondary",
  paused: "secondary",
  finished: "secondary",
  draft: "secondary",
  disconnected: "secondary",
  soon: "secondary"
};

export function StatusBadge({ status }: { status: string }) {
  return (
    <Badge variant={variants[status] ?? "secondary"}>
      {labels[status] ?? status}
    </Badge>
  );
}
